name: randomnwn
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.22.0
  - networkx=2.5.1
  - scipy=1.6.2
  - Shapely=1.7.1
  - matplotlib=3.3.4
  - ipykernel
  - line_profiler
  - joblib
  - pip
